depedencies_apps=(
    git
    curl
    wget
    fuse
    libfuse2
    dunst
    libnautilus-extension1a
    arp-scan
    python3
    python3-pip
    python3-venv
    python3-requests 
    python3-setuptools
    python3-dev
    python3-dnspython
    python3-dns
    python3-venv
    python3-nautilus 
    python3-gi
    nautilus-python
    nautilus-data
    nautilus-admin
    nautilus-image-converter
    imagemagick
    battery-stats
    git-delta
    ffmpeg
    pipx
    binutils-gold 
    gcc 
    libcurl4-openssl-dev 
    libedit-dev 
    libicu-dev 
    libncurses-dev 
    libpython3-dev 
    libsqlite3-dev 
    libxml2-dev 
    pkg-config 
    tzdata 
    uuid-dev
    cmatrix
    gotop
    build-essential 
    autojump
    sysstat 
    ifstat
    net-tools 
    iftop 
    iperf3 
    nmtui
    speedtest-cli 
    speed
    sd
    taskwarrior
    tee
    ruby-dev
    ruby-full
    xrandr
    xdotool
    xclip
    xsel
    devilspie2
    fonts-font-awesome
    appmenu-gtk-module-common
    libdbusmenu-gtk3-4
    libdbusmenu-qt5-2
    vala-panel-appmenu
    appmenu-qt5
    poppler-utils 
    awscli
)