code --install-extension aaron-bond.better-comments-3.0.2
code --install-extension batisteo.vscode-django-1.15.0
code --install-extension bmewburn.vscode-intelephense-client-1.14.3
code --install-extension brapifra.phpserver-3.0.2
code --install-extension charliermarsh.ruff-2025.14.0-linux-x64
code --install-extension christian-kohler.path-intellisense-2.10.0
code --install-extension cocopon.iceberg-theme-2.0.4
code --install-extension continue.continue-1.0.3-linux-x64
code --install-extension dart-code.dart-code-3.106.0
code --install-extension dart-code.flutter-3.106.0
code --install-extension davidanson.vscode-markdownlint-0.59.0
code --install-extension davidbwaters.macos-modern-theme-2.3.19
code --install-extension dbaeumer.vscode-eslint-3.0.10
code --install-extension donjayamanne.python-environment-manager-1.2.7
code --install-extension donjayamanne.python-extension-pack-1.7.0
code --install-extension dsznajder.es7-react-js-snippets-4.4.3
code --install-extension ecmel.vscode-html-css-2.0.13
code --install-extension esbenp.prettier-vscode-11.0.0
code --install-extension formulahendry.auto-rename-tag-0.1.10
code --install-extension formulahendry.code-runner-0.12.2
code --install-extension golang.go-0.46.1
code --install-extension jamiewoodio.cisco-1.9.1
code --install-extension kevinrose.vsc-python-indent-1.21.0
code --install-extension mechatroner.rainbow-csv-3.18.0
code --install-extension ms-azuretools.vscode-docker-1.29.4
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools-1.3.20
code --install-extension ms-python.black-formatter-2025.2.0
code --install-extension ms-python.debugpy-2025.4.1-linux-x64
code --install-extension ms-python.isort-2023.10.1
code --install-extension ms-python.python-2025.2.0-linux-x64
code --install-extension ms-python.vscode-pylance-2025.3.1
code --install-extension ms-toolsai.jupyter-2025.2.0-linux-x64
code --install-extension ms-toolsai.jupyter-keymap-1.1.2
code --install-extension ms-toolsai.jupyter-renderers-1.1.0
code --install-extension ms-toolsai.vscode-jupyter-cell-tags-0.1.9
code --install-extension ms-toolsai.vscode-jupyter-slideshow-0.1.6
code --install-extension ms-vscode.cmake-tools-1.20.53
code --install-extension ms-vscode.cpptools-1.24.2-linux-x64
code --install-extension ms-vscode.cpptools-extension-pack-1.3.1
code --install-extension ms-vscode.cpptools-themes-2.0.0
code --install-extension ms-vscode.powershell-2025.0.0
code --install-extension ms-vscode.remote-explorer-0.4.3
code --install-extension ms-vscode-remote.remote-containers-0.401.0
code --install-extension ms-vscode-remote.remote-ssh-0.118.0
code --install-extension ms-vscode-remote.remote-ssh-edit-0.87.0
code --install-extension ms-vscode-remote.remote-wsl-0.88.5
code --install-extension ms-vsliveshare.vsliveshare-1.0.5948
code --install-extension mtxr.sqltools-0.28.4
code --install-extension mtxr.sqltools-driver-mysql-0.6.4
code --install-extension mtxr.sqltools-driver-sqlite-0.5.2
code --install-extension mutantdino.resourcemonitor-1.0.7
code --install-extension njpwerner.autodocstring-0.6.1
code --install-extension oderwat.indent-rainbow-8.3.1
code --install-extension pkief.material-icon-theme-5.20.0
code --install-extension postman.postman-for-vscode-1.8.1
code --install-extension qwtel.sqlite-viewer-0.10.2-linux-x64
code --install-extension redhat.ansible-25.2.0
code --install-extension redhat.java-1.40.0-linux-x64
code --install-extension redhat.vscode-extension-dashbuilder-editor-0.32.0
code --install-extension redhat.vscode-extension-dmn-editor-0.26.0
code --install-extension redhat.vscode-kaoto-2.4.0
code --install-extension redhat.vscode-openshift-connector-1.18.0-linux-x64
code --install-extension redhat.vscode-redhat-account-0.2.0
code --install-extension redhat.vscode-rsp-ui-0.24.11
code --install-extension redhat.vscode-xml-0.28.0-linux-x64
code --install-extension redhat.vscode-yaml-1.17.0
code --install-extension ritwickdey.liveserver-5.7.9
code --install-extension rust-lang.rust-analyzer-0.3.2337-linux-x64
code --install-extension s-nlf-fh.glassit-0.2.6
code --install-extension samuelcolvin.jinjahtml-0.20.0
code --install-extension silofy.hackthebox-0.2.9
code --install-extension streetsidesoftware.code-spell-checker-4.0.40
code --install-extension tabnine.tabnine-vscode-3.241.0
code --install-extension techer.open-in-browser-2.0.0
code --install-extension twxs.cmake-0.0.17
code --install-extension usernamehw.errorlens-3.24.0
code --install-extension visualstudioexptteam.intellicode-api-usage-examples-0.2.9
code --install-extension visualstudioexptteam.vscodeintellicode-1.3.2
code --install-extension vscjava.vscode-java-debug-0.58.1
code --install-extension whizkydee.material-palenight-theme-2.0.4
code --install-extension wholroyd.jinja-0.0.8
code --install-extension xabikos.javascriptsnippets-1.8.0
code --install-extension xdebug.php-debug-1.35.0
code --install-extension xdebug.php-pack-1.0.3
code --install-extension yurialvesguernsey.localastrodb-2.0.0
code --install-extension zobo.php-intellisense-1.3.3
code --install-extension .9b54e618-2201-4390-a6cc-df26bf6f4365
code --install-extension blackboxapp.blackboxagent-2.8.29